### ISSUE TITLE
Network timeout pass through support needed

### ISSUE THREAD

**Issue by jhargis** [paypal/paypalhttp_python#13]
### Lib versions

* SDK/Library version: 1.0.1
* Python Version: 3.10.1

### Details

The [Requests](https://github.com/psf/requests) library used by paypalhttp_python supports network connection timeouts 
https://github.com/psf/requests/blob/177dd90f18a8f4dc79a7d2049f0a3f4fcc5932a0/requests/sessions.py#L538

But paypalhttp_python is not providing pass through support for the argument.
https://github.com/paypal/paypalhttp_python/blob/72609783230663b8e34c6f0384837db7b166c8f4/paypalhttp/http_client.py#L55

When the remote (PayPal) does not respond, the connection hangs and the worker process goes zombie. Please provide a pass through so monkey patching is not required.

**Comment by devchristina** [comment]
Hi @jhargis -- apologies that it's taken this long for anyone to reply from the PayPal side. Due to the age of this issue and the fact that this SDK is using old integration patterns & deprecated endpoints, I am going to close this issue without action and will add a "deprecated" status to the repo. Thank you for your understanding. If there are any issues you face, please let me know and we can look into it.
